- name: Playbook demonstrates accessing vault protected data from ansible playbook
  hosts: localhost
  vars_files:
  - mysql-login-credentials.yml
  tasks:
  - debug: msg="username={{username}}, password={{password}}" 
