- name: Check if nginx web server is already running in Rocky ansible nodes
  shell: curl http://localhost:80
  register: output
  ignore_errors: yes

- debug: var=output

- name: Start nginx web server in Rocky ansible nodes 
  when: output.rc != 0
  shell: nginx 
